version: "3.8"
services:
  backend:
    build: .
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb+srv://manu:manu@cluster0.wger0.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
  mongo:
    image: mongo
    ports:
      - "27017:27017"
